type EventsType = {
    ON_LEAVE_ROOM: string,
    LOGOUT: string,
    ROOMS: string,
    NEW_ROOM_UPDATE: string,
    NEW_USER_ADDED: string,
    USER_LEAVE_ROOM: string,
    UPDATE_ROOM_ON_CREATE: string,
    ON_JOIN: string,
    ON_ROOM_FULL: string,
    UPDATE_ROOM_USERS: string,
    ALL_USER_IN_CURRENT_ROOM: string,
    GET_MESSAGE: string,
    SEND_MESSAGE: string,
    ON_TYPING_START: string
    ON_TYPING_STOP: string,
    ON_TYPING: string,
    NOT_FILE_ALLOWED: string,
    ADMIN_INFO: string,
    KICKOUT: string,
    KICKOUT_USER: string,
    AFTER_KICKOUT_USER_TO_GET_ALL_USER: string,
    BROADCAST_MESSAGE_TO_GLOBAL_USER: string,
    NEW_USER_ADDED_ALL:string

}
export const EVENTS: EventsType = {
    ON_LEAVE_ROOM: "onLeaveRoom",
    LOGOUT: "logout",
    ROOMS: "rooms",
    NEW_ROOM_UPDATE: "newRoomUpdate",
    NEW_USER_ADDED: "newUserAdded",
    USER_LEAVE_ROOM: "userleftRoom",
    UPDATE_ROOM_ON_CREATE: "update_room_on_create",
    ON_JOIN: "on_join",
    ON_ROOM_FULL: "on_room_full",
    UPDATE_ROOM_USERS: "update_room_users",
    ALL_USER_IN_CURRENT_ROOM: "alluserInCurrentRoom",
    GET_MESSAGE: "get_msg",
    SEND_MESSAGE: "send_msg",
    ON_TYPING_START: "onTyping-start",
    ON_TYPING_STOP: "onTyping-stop",
    ON_TYPING: "onTyping",
    NOT_FILE_ALLOWED: "fileNotAllowed",
    ADMIN_INFO: "admin_info",
    KICKOUT: "kickout",
    KICKOUT_USER: "kickoutUser",
    AFTER_KICKOUT_USER_TO_GET_ALL_USER: "kickoutUserToAll",
    BROADCAST_MESSAGE_TO_GLOBAL_USER: "userleaveRoom",
    NEW_USER_ADDED_ALL:"newUserAdded_ALL"
}